# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/a3Servicer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import a3_pb2 as protos_dot_a3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/a3Servicer.proto\x12\x06protos\x1a\x0fprotos/a3.proto\"/\n\x11\x43reateBookRequest\x12\x1a\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0c.protos.Book\"I\n\x12\x43reateBookResponse\x12\"\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x14.protos.ResponseCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"v\n\x0fGetBookResponse\x12\"\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x14.protos.ResponseCode\x12\x1c\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x0c.protos.BookH\x00\x12\x11\n\x07message\x18\x03 \x01(\tH\x00\x42\x0e\n\x0cresponseType*\"\n\x0cResponseCode\x12\x07\n\x03\x45RR\x10\x00\x12\t\n\x05NOERR\x10\x01\x32\x91\x01\n\na3Servicer\x12\x45\n\nCreateBook\x12\x19.protos.CreateBookRequest\x1a\x1a.protos.CreateBookResponse\"\x00\x12<\n\x07GetBook\x12\x16.protos.GetBookRequest\x1a\x17.protos.GetBookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.a3Servicer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSECODE._serialized_start=328
  _RESPONSECODE._serialized_end=362
  _CREATEBOOKREQUEST._serialized_start=52
  _CREATEBOOKREQUEST._serialized_end=99
  _CREATEBOOKRESPONSE._serialized_start=101
  _CREATEBOOKRESPONSE._serialized_end=174
  _GETBOOKREQUEST._serialized_start=176
  _GETBOOKREQUEST._serialized_end=206
  _GETBOOKRESPONSE._serialized_start=208
  _GETBOOKRESPONSE._serialized_end=326
  _A3SERVICER._serialized_start=365
  _A3SERVICER._serialized_end=510
# @@protoc_insertion_point(module_scope)
